name: CI
on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'

  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'

  workflow_dispatch:

jobs:
  ci:
    uses: cthulhu-oidc/workflows/.github/workflows/ci.yml@master
    with:
      licenseCheck: true
      lint: true
      logic: true
      types: true
      coverage: true
