name: CI
on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'

  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'

  workflow_dispatch:
    inputs:
      licenseCheck:
        description: 'Check Licenses'     
        required: false
        type: boolean
        default: true
      lint:
        description: 'Lint'     
        required: false
        type: boolean
        default: true
      logic:
        description: 'Test Logic'     
        required: false
        type: boolean
        default: true
      types:
        description: 'Test Types'     
        required: false
        type: boolean
        default: true
      coverage:
        description: 'Code Coverage'     
        required: false
        type: boolean
        default: true
jobs:
  ci:
    uses: cthulhu-oidc/workflows/.github/workflows/ci.yml@master
    with:
      licenseCheck: >
        (github.event_name == 'workflow_dispatch' &&  github.events.inputs.licenseCheck == true) ||
        (github.event_name != 'workflow_call')
      lint:  >
        (github.event_name == 'workflow_dispatch' &&  github.events.inputs.lint == true) ||
        (github.event_name != 'workflow_call')
      logic:  >
        (github.event_name == 'workflow_dispatch' &&  github.events.inputs.logic == true) ||
        (github.event_name != 'workflow_call')
      types:  >
        (github.event_name == 'workflow_dispatch' &&  github.events.inputs.types == true) ||
        (github.event_name != 'workflow_call')
      coverage:  >
        (github.event_name == 'workflow_dispatch' &&  github.events.inputs.coverage == true) ||
        (github.event_name != 'workflow_call')
