name: CI
on:
  workflow_dispatch:
    inputs:
      licenseCheck:
        description: 'Check Licenses'     
        required: false
        type: boolean
        default: true
      lint:
        description: 'Lint'     
        required: false
        type: boolean
        default: true
      logic:
        description: 'Test Logic'     
        required: false
        type: boolean
        default: true
      types:
        description: 'Test Types'     
        required: false
        type: boolean
        default: true
      coverage:
        description: 'Code Coverage'     
        required: false
        type: boolean
        default: true
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'

jobs:
  ci:
    uses: cthulhu-oidc/.github/workflows/ci.yml@vmaster
    with:
      licenseCheck: true
      lint: true
      logic: true
      types: true
      coverage: true