name: CI
on:
  workflow_call:
    inputs:
      licenseCheck:
        description: 'Check Licenses'     
        required: false
        type: boolean
        default: true
      lint:
        description: 'Lint'     
        required: false
        type: boolean
        default: true
      logic:
        description: 'Test Logic'     
        required: false
        type: boolean
        default: true
      types:
        description: 'Test Types'     
        required: false
        type: boolean
        default: true
      coverage:
        description: 'Code Coverage'     
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      licenseCheck:
        description: 'Check Licenses'     
        required: false
        type: boolean
        default: true
      lint:
        description: 'Lint'     
        required: false
        type: boolean
        default: true
      logic:
        description: 'Test Logic'     
        required: false
        type: boolean
        default: true
      types:
        description: 'Test Types'     
        required: false
        type: boolean
        default: true
      coverage:
        description: 'Code Coverage'     
        required: false
        type: boolean
        default: true
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'

jobs:
  licenseCheck:
    if: >
      !failure() &&
      !cancelled() &&
      (
        github.event_name == 'workflow_call' && inputs.licenseCheck != 'false' ||
        github.event_name == 'workflow_dispatch' && github.event.inputs.licenseCheck != 'false' ||
        github.event_name == 'pull_request' ||
        github.event_name == 'push'
      )
    name: Check Licenses
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: check-cache
        with:
          path: ~/.npm
          key: node-18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-18-

      - run: npm install
      - name: Install License-Checker globally
        run: npm i -g license-checker

      - name: Check Licenses
        run: npx license-checker --production --onlyAllow="MIT;ISC;BSD-3-Clause;BSD-2-Clause"

  lint:
    if: >
      !failure() &&
      !cancelled() &&
      (
        github.event_name == 'workflow_call' && inputs.lint != 'false' ||
        github.event_name == 'workflow_dispatch' && github.event.inputs.lint != 'false' ||
        github.event_name == 'pull_request' ||
        github.event_name == 'push'
      )
    needs:
      - licenseCheck
    name: Lint TS-Files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: 18
      
      - uses: actions/cache@v3
        id: check-cache
        with:
          path: ~/.npm
          key: node-18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-18-

      - run: npm install

      - name: Lint TS-Files
        run: npm run lint

  logic:
    name: Test Logic on Node ${{ matrix.node }}
    if: >
      !failure() &&
      !cancelled() &&
      (
        github.event_name == 'workflow_call' && inputs.logic != 'false' ||
        github.event_name == 'workflow_dispatch' && github.event.inputs.logic != 'false' ||
        github.event_name == 'pull_request' ||
        github.event_name == 'push'
      )
    needs:
      - lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v3
        id: check-cache
        with:
          path: ~/.npm
          key: node-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-${{ matrix.node-version }}-

      - run: npm install
      - run: npm run test:ts

  types:
    if: >
      !failure() &&
      !cancelled() &&
      (
        github.event_name == 'workflow_call' && inputs.types != 'false' ||
        github.event_name == 'workflow_dispatch' && github.event.inputs.types != 'false' ||
        github.event_name == 'pull_request' ||
        github.event_name == 'push'
      )
    name: Test Typescript Types
    needs:
      - logic
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: check-cache
        with:
          path: ~/.npm
          key: node-18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-18-

      - run: npm install
      - run: npm run test:types

  coverage:
    if: >
      !failure() &&
      !cancelled() &&
      (
        github.event_name == 'workflow_call' && inputs.coverage != 'false' ||
        github.event_name == 'workflow_dispatch' && github.event.inputs.coverage != 'false' ||
        github.event_name == 'pull_request' ||
        github.event_name == 'push'
      )
    name: Coverage on Node 18
    needs:
      - types
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node 18
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: check-cache
        with:
          path: ~/.npm
          key: node-18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-18-

      - run: npm install
      - run: npm run test:coverage

  automerge:
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.user.login == 'dependabot[bot]'
    needs: 
      - coverage
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
