name: CI
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      pr-number:
        description: an id of an pull request
        required: false
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'src'
      - 'spec'

jobs:
  lint:
    name: Lint TS-Files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: 18

      - run: npm install

      - name: Lint TS-Files
        run: npm run lint

  logic:
    name: Test Logic on Node ${{ matrix.node }}
    needs:
      - lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run test:ts

  coverage:
    name: Coverage on Node 18
    needs:
      - lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node 18
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: 18

      - run: npm install
      - run: npm run test:coverage

  types:
    name: Test Typescript Types
    needs:
      - logic
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: 18

      - run: npm install
      - run: npm run test:types

  automerge:
    if: github.event_name == 'pull_request'
    needs: 
      - types
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.inputs.pr-number }}
