name: Publish nightly build to npmjs
on:
  schedule:
    - cron:  '0 7 * * *'
  # enable users to manually trigger with workflow_dispatch
  workflow_dispatch: {}
  repository_dispatch:
    types: publish-nightly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish nightly
        run: |
          npm whoami
          npm i
          npm run test
          npm run clean
          npm run build
          npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true
