name: Publish nightly build to npmjs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for changes in the last 24h
        id: hasChanges
        run: if [ "$(expr $(git log -1 --format=%ct) + 86400)" -gt "$(date +%s)" ]; then echo true; else echo false; fi
      - name: Use node version 18
        if: steps.hasChanges.outcome == true
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish next
        if: steps.hasChanges.outcome == true
        run: |
          npm i
          npm run build
          npm run prepare:next
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
