name: Publish next build to npmjs
on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/workflows/ci

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish next
        run: |
          npm i
          npm run build
          npm run prepare:next
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
