name: Publish on npm
on:
  release:
    types:
      - released
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Bump version
        run: |
          git fetch
          git checkout ${RELEASE_BRANCH}
          npm --no-git-tag-version version ${RELEASE_TAG/refs\/tags\/v/}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./package.json
          git commit -m "Bump version to ${RELEASE_TAG/refs\/tags\/v/}"
          git push origin HEAD:${RELEASE_BRANCH}
          git tag -f ${RELEASE_TAG/refs\/tags\//}
        env:
          RELEASE_TAG: ${{github.ref}}
          RELEASE_BRANCH: ${{github.event.release.target_commitish}}

      - name: Publish on npm
        run: |
          npm i
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          