name: Publish nightly build to npmjs
on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 16
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish next
        run: |
          let TMP=$(git log -1 --format=%ct)+86400
          if [ "$TMP" -gt "$(date +%s)" ]; then exit; fi
          npm i
          npm run build
          npm run prepare:next
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
