name: Publish nightly build to npmjs
on:
  workflow_call:
    inputs:
      timespan:
        description: 'The timespan since the last commit'     
        required: true
        type: "string"
        default: "86400"
  workflow_dispatch:
    inputs:
      timespan:
        description: 'The timespan since the last commit'     
        required: true
        type: "string"
        default: "86400"
  schedule:
    - cron: '0 0 * * *'

jobs:
  changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Check for changes
        id: hasChanges
        run: if [ "$(expr $(git log -1 --format=%ct) + $TIMESPAN)" -gt "$(date +%s)" ]; then echo ::set-output name=hasChanges::true; else echo ::set-output name=hasChanges::false; fi
        env:
          TIMESPAN: ${{ inputs.timespan || github.event.inputs.timespan || 86400 }}
    outputs:
      hasChanges: ${{ steps.hasChanges.outputs.hasChanges }}

  ci:
    needs:
      - changed
    if: ${{ !failure() && !cancelled() && needs.changed.outputs.hasChanges == 'true' }}
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    if: ${{ !failure() && !cancelled() && needs.changed.outputs.hasChanges == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Use node version 18
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - uses: actions/cache@v3.0.3
        id: check-cache
        with:
          path: ~/.npm
          key: node-18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-18-
        
      - name: Setup and publish next
        run: |
          npm install
          npm run build
          npm run prepare:next
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
