name: Publish next build to npmjs
on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3.0.2
      - name: Use node version 16
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - uses: actions/cache@v3.0.2
        id: check-cache
        with:
          path: ~/.npm
          key: node-18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-18-

      - name: Setup and publish next
        run: |
          npm install
          npm run build
          npm run prepare:next
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
