name: Publish nightly build to npmjs
on:
  workflow_dispatch:
    inputs:
      timespan:
        description: 'The timespan since the last changes were made'     
        required: true
        type: "string"
        default: "86400"
  schedule:
    - cron: '0 0 * * *'

jobs:
  changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for changes
        id: hasChanges
        run: if [ "$(expr $(git log -1 --format=%ct) + $TIMESPAN)" -gt "$(date +%s)" ]; then echo ::set-output name=hasChanges::true; else echo ::set-output name=hasChanges::false; fi
        env:
          TIMESPAN: ${{ github.event.inputs.timespan || 86400 }}
    outputs:
      hasChanges: ${{ steps.hasChanges.outputs.hasChanges }}

  test:
    needs: changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ needs.changed.outputs.hasChanges }}
  ci:
    needs:
      - changed
    if: ${{ !failure() && !cancelled() && needs.changed.outputs.hasChanges == true }}
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    if: ${{ !failure() && !cancelled() && needs.changed.outputs.hasChanges == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish next
        if: steps.hasChanges.outcome == true
        run: |
          npm i
          npm run build
          npm run prepare:next
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
