name: Release
on:
  release:
    types:
      - published
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish next
        run: |
          git checkout ${RELEASE_BRANCH}
          npm whoami
          npm i
          npm run test
          npm run clean
          npm run build
          npm version ${RELEASE_TAG/\/refs\/tags\/v/}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          RELEASE_TAG: ${{github.release.tag_name}}
          RELEASE_BRANCH: ${{github.release.target_commitish}}
          CI: true
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'package.json'
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          message: Release ${{github.release.tag_name}} on npm 
          