name: Release
on:
  release:
    types:
      - released
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Bump version and modify changelog
        run: |
          git fetch
          git checkout ${RELEASE_BRANCH}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          npm --no-git-tag-version version ${RELEASE_TAG_NAME/v/}
          git add ./package.json

          touch CHANGELOG.md
          echo -e "${RELEASE_TAG_NAME/v/} / $(date +%Y-%m-%d)\n==================\n\n$RELEASE_BODY \n\n $(cat CHANGELOG.md)" > CHANGELOG.md
          git add ./CHANGELOG.md

          git commit -m "Release ${RELEASE_TAG_NAME/v/}"
          git push origin HEAD:${RELEASE_BRANCH}
          git tag -f ${RELEASE_TAG_NAME}
        env:
          RELEASE_NAME: ${{github.release.name}}
          RELEASE_BODY: ${{github.release.body}}
          RELEASE_TAG_NAME: ${{github.release.tag_name}}
          RELEASE_BRANCH: ${{github.event.release.target_commitish}}

      - uses: actions/cache@v3
        id: check-cache
        with:
          path: ~/.npm
          key: node-18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-18-

      - name: Publish on npm
        run: |
          npm i
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          