name: Unpublish on npm
on:
  release:
    types:
      - deleted

jobs:
  unpublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Unpublish on npm
        run: |
          npm unpublish $(awk '/name/{gsub(/("|",)/,"",$2);print $2}' package.json)@${RELEASE_TAG/refs\/tags\/v/}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          RELEASE_TAG: ${{github.ref}}